### PR TITLE
[dpub-pwp] rewrite of section on archive formats

### PR DESCRIPTION
**Pull request by dauwhe**
I've rewritten the section on archive formats.

### CODE REVIEW

**Review by TzviyaSiegman — COMMENTED** [review]
clear and succinct. I like this edit.

**Comment by iherman** [comment]
My only (minor!) remark is that you also removed this sentence:

> Nevertheless, if browsers, eventually, do converge towards a browser and streaming friendly packaging format, adopting it for <a>Packaged Web Publications</a> may become a real alternative. 

I think keeping (in some format) this sentence at the end of the paragraph on Web Packaging might be a good idea. In some way, it shows that we are seriously considering to align on OWP wherever this is possible.

That being said: I do not consider this as overly important. I am all in favour merging this PR with or without that additional remark.

Thanks!!!

**Comment by dauwhe** [comment]
@iherman, I've merged the PR and then added back a similar sentence on adopting a browser-supported packaging format. I don't yet know how to edit a PR :)

**Comment by iherman** [comment]
> 
> @iherman <https://github.com/iherman>, I've merged the PR and then added back a similar sentence on adopting a browser-supported packaging format. I don't yet know how to edit a PR :)
> 
Great!

**Pull request merged**
